# Generated by Django 2.2.5 on 2019-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_vid', models.CharField(max_length=11)),
                ('stars_count', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category_id', models.IntegerField(choices=[(1, 'HTML/CSS'), (2, 'JavaScript'), (3, 'Python'), (4, 'Django')])),
                ('skill_level_id', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-stars_count', 'title'],
            },
        ),
    ]
